### ISSUE TITLE
Instructions are not clear.

### ISSUE THREAD

**Issue by psycholyzern** [infoshift/gsmarena-scraper#2]
Hi, I want to use the save-to-db branch but I couldnt figure out how to scrape url of all phone models into ```input/phones.csv```
Do I need to put the url one by one manually or what?

Thanks.

**Comment by carlloiuse** [comment]
In save-to-db, it automatically searches for the gsmarena link from the given tac,manufacturer,model in inputs/phones.csv then do the data scraping. However, you can do that in the master branch where you put the actual gsmarena URL in filtered_urls.csv and the application will do the scraping for you.

**Comment by psycholyzern** [comment]
Oh so I need to put the tac, manufacturer, model manually?
Then it will scrape based on what I out in there?

**Comment by carlloiuse** [comment]
in save-to-db branch, yes
